language: dart
sudo: required
addons:
  chrome: stable

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

dart:
  - 1.24.3
  - stable

script:
  - npm install
  - dartfmt --set-exit-if-changed -n lib test example
  - dartanalyzer lib test example
  - tool/test.sh
